"""change in shopping cart item

Revision ID: 0dd66432ceae
Revises: 69fb20912fb6
Create Date: 2024-01-13 23:49:50.111989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd66432ceae'
down_revision: Union[str, None] = '69fb20912fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_cart',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('shopping_cart_items', sa.Column('shopping_cart_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shopping_cart_items', 'shopping_cart', ['shopping_cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_cart_items', type_='foreignkey')
    op.drop_column('shopping_cart_items', 'shopping_cart_id')
    op.drop_table('shopping_cart')
    # ### end Alembic commands ###
