"""create_order_threshold

Revision ID: 69fb20912fb6
Revises: 0a33cd781de5
Create Date: 2024-01-13 16:46:31.049602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fb20912fb6'
down_revision: Union[str, None] = '0a33cd781de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customers', ['id'])
    op.create_unique_constraint(None, 'discounts', ['id'])
    op.create_unique_constraint(None, 'order_items', ['id'])
    op.create_unique_constraint(None, 'product_categories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_categories', type_='unique')
    op.drop_constraint(None, 'order_items', type_='unique')
    op.drop_constraint(None, 'discounts', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    # ### end Alembic commands ###
