"""create_verification

Revision ID: 8e164b4da594
Revises: 387ac52c0891
Create Date: 2024-01-13 14:27:22.427930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e164b4da594'
down_revision: Union[str, None] = '387ac52c0891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departments', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'shopping_cart_items', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'shopping_cart_items', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'departments', type_='unique')
    # ### end Alembic commands ###
